/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rzingle' at '5/16/16 7:03 PM' with Gradle 2.13
 *
 * @author rzingle, @date 5/16/16 7:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
